### ISSUE TITLE
Would be great to get some information about this fork

### ISSUE THREAD

**Issue by copernicus365** [Ionaru/easy-markdown-editor#1]
Hi there, looks like you've been adding some good stuff to simplemde, while the main simplemde project hasn't been updated for 2 years (unless I'm reading it wrong). Any chance you could post some information about this fork? Thanks

**Comment by Ionaru** [comment]
You're right, the original project hasn't had any activity for nearly two years.

I'd be happy to post some info, what would you like to know?

**Comment by copernicus365** [comment]
Thanks for the reply. I found your fork by browsing thru this page (https://github.com/sparksuite/simplemde-markdown-editor/network), and checking out some of those forks. I certainly could be missing a major one, but your commits seem to be the only fork I've seen thus far that is actually a general purpose improvement of the library, rather than just being minor little changes, or idiosyncratic ones (not general purpose). Would you say that is true? And is there a rhyme or reason to the changes you are making?

I see your commits are still under a development branch, but just wondering if you would give a thumbs up (no warranty included of course 😉) that you think your fork is an overall bettered version, which people might want to therefore consider using instead.

**Comment by Ionaru** [comment]
I started this fork originally to put FA5 support in via pull-request, I needed that for a project I was working on. My plan now is to make this version of simplemde better than the original, and continue development on it. So yeah I'd say it's a general purpose improvement.

So far I've just been fixing things that were bugging me personally, I haven't had the time to go over all the code but there are some other improvements I want to make. One of them is the `isMobile()` function because holy crap what even is that?!

From what I've seen of the current development branch, I think it's better than the current simplemde version on NPM, yes. But keep in mind that I didn't do any extensive testing on it.

**Comment by copernicus365** [comment]
Terrific! I'm already testing out your fork and it's working great thus far. Thanks for your work.

> "One of them is the isMobile() function because holy crap what even is that?!"
😆 
"FA5" ?

**Comment by Ionaru** [comment]
FA5 = FontAwesome 5

**Comment by MayMeow** [comment]
Hi. This fork will be available to install via npm?

**Comment by Ionaru** [comment]
Yes I do plan to release this version of SimpleMDE on NPM, but there are a few things I want to do first. One is to come up with a new name for the project, because `simplemde` is already taken, also I want to edit the README a bit, simplify it and set up a demo site for the project.

**Comment by Ionaru** [comment]
Closing this, `EasyMDE` is now released on NPM! :tada:
