### ISSUE TITLE
New line after list

### ISSUE THREAD

**Issue by mobeendude** [Ionaru/easy-markdown-editor#15]
I'm submitting a... Bug report..

### Reproduction steps
I am using it as a replacement for simplemde.
1. There is a  difference in markdown  rendering in preview mode when using list.  The very next line (dont have to leave any blank space),  in preview mode is rendered differently. The content of next line shows up on last line of list (ignoring \n)
2. Also markdown is also a bit different. (On  Simplemde, we had markdown \r\n on new line but on this version, its only \n

### Version information
Browser type and version: Chrome
EasyMDE version: v2.1.0

**Comment by Ionaru** [comment]
1. That the very next line after a list shows up in the list (but without a dot) is a quirk of Markdown, and not something I can fix in the editor. Try it out in the GitHub editor and you'll see the same behaviour.

2. Going from \r\n to \n is not a change I made intentionally, but I don't see how it would cause any issues because the rendered markdown should be the same. Is this causing a problem for you?

**Comment by mobeendude** [comment]
Thanks @Ionaru , for replying.

For 2 , I assumed it was causing the issue I mention in point 1. But I have checked by adding '\r' manually and it doesnt solves it. 

For 1, The markdown preview and markdown I am rendering using marked library is in-consistent. One  ignores new line and the other doesnt.

**Comment by mobeendude** [comment]
Adding  these as options when using marked library displays it in new line.  :)   Thanks. Just one last query: are these are defaults in easymde markdown renderer ?

gfw: true, breaks: true
