### ISSUE TITLE
Easy-mde doesn't work well with `inputStyle: 'contenteditable'` 

### ISSUE THREAD

**Issue by A-312** [Ionaru/easy-markdown-editor#160]
#143 Introduce inputStyle: 'contenteditable'

I experienced some weird bugs with easy-mde (getCursor and setCursor didn't work fine). I have figured out why: `inputStyle: 'contenteditable'` doesn't work as well than `inputStyle: 'textarea'`. https://discuss.codemirror.net/t/is-the-textarea-inputstyle-going-to-be-deprecated-in-the-future/1278

### Work well with `inputStyle: 'textarea'`

![image2 1](https://user-images.githubusercontent.com/18501150/75721582-e9988680-5cd8-11ea-8138-19d55acec48a.gif)

### Don't work well with `inputStyle: 'contenteditable'`

![image2 2](https://user-images.githubusercontent.com/18501150/75721841-5744b280-5cd9-11ea-8be8-b94961395d46.gif)

(don't work well because the mouse go on the begining after a click)

**Comment by A-312** [comment]
Selection was fixed by [5.52.0](https://github.com/codemirror/CodeMirror/commit/a5f44b43e27e5960d9e9c3ba45b2a7e27766c1ec#diff-447dce4c9d47571c21c30c8f59308d86) of codemirror.

**Comment by mxgl** [comment]
I may be wrong here, but I've dealt with a similar issue trying to get zurb/tribute integrated with easyMDE. 

It seems when anything not native to codemirror occurs, the cursor location isn't preserved.

I've had to do a getCursor, then do my action, followed by a setCursor. This has worked well enough, but is not perfect. 

the issue is more with CodeMirror's cursor positioning in contenteditables.

**Comment by A-312** [comment]
I made a fix on codemirror https://github.com/codemirror/CodeMirror/pull/6168 but I think we have to set `options.forceFocus` to `true` like this:

`editor.setSelection({line:0, ch:2}, {line:0, ch:5}, {forceFocus:true})`.
