### ISSUE TITLE
Relation to InscrybMDE

### ISSUE THREAD

**Issue by GenaBitu** [Ionaru/easy-markdown-editor#36]
Hi, I've been looking for a (maintained) replacement to SimpleMDE and found this and [InscrybMDE](https://github.com/Inscryb/inscryb-markdown-editor) - what is the relation between the forks? I would really like to have my cake and eat it all :D

**Comment by GenaBitu** [comment]
Related issue: Inscryb/inscryb-markdown-editor#38

**Comment by Ionaru** [comment]
InscribMDE is a fork made of EasyMDE not long after that was forked from SimpleMDE. Both projects seem to have similar directions since then: keeping packages up-to-date, fixing critical bugs and adding a few new features.

EasyMDE grew from my desire to have FontAwesome 5 compatibility in SimpleMDE (https://github.com/sparksuite/simplemde-markdown-editor/pull/666), but that pull request was never accepted.

Since then I've worked on keeping this editor alive by adding requested features, fixing bugs and making internal changes to make maintaining the editor easier.

**Comment by CWharton** [comment]
@Ionaru Sorry but you are mistaken, InscrybMDE is not a fork of EasyMDE. It is a fork of SimpleMDE. We created it because we couldn't find an active fork of SimpleMDE at the time and the owner of SimpleMDE was not interested in maintaining his project anymore.

**Comment by Ionaru** [comment]
@CWharton Sure the project wasn't named EasyMDE back then, the name change was made later. However the repositories are sharing some commits from after I made the fork from SimpleMDE, meaning it was forked from here after commit https://github.com/Ionaru/easy-markdown-editor/commit/c34cebefd6bf5b1e96af7b8880a07ee5defd10c4 -> https://github.com/Inscryb/inscryb-markdown-editor/commit/c34cebefd6bf5b1e96af7b8880a07ee5defd10c4.

This is visible at https://github.com/Inscryb/inscryb-markdown-editor/commits/master?after=3ea6e6ee6251286bab52b6681a0068dc5c2061e6+0

**Comment by CWharton** [comment]
@Ionaru my apologies I stand corrected. It has been a while and I must have forgotten about it. If you are interested in maintaining as it seems you are. Maybe we should consider joining efforts.

**Comment by Ionaru** [comment]
Agreed, that is a good idea.
We should talk about how we can accomplish this, I can be contacted on Discord: `Ionaru#3801`.

In the meantime I'm closing this issue as I think the question has been answered.
