### ISSUE TITLE
Unexpected text deletion when selecting content with backticks

### ISSUE THREAD

**Issue by silverwind** [Ionaru/easy-markdown-editor#408]
**Describe the bug**
When backtick characters are present, the editor will unexpectedly delete text during selection.

**To Reproduce**
- Go to https://easy-markdown-editor.tk/
- Enter single ``` ` ``` character into editor
- Select the character via either mouse drag or double-click
- Character is unexpectedly deleted

**Expected behavior**
Text should never be deleted during selection

**Comment by Ionaru** [comment]
Could not reproduce, can you give some more information like browser, OS and record a video of it?

**Comment by silverwind** [comment]
Firefox 98 on macOS 12. It appears to be a Firefox-only issue, can not reproduce in Chrome. Here's how it looks, I enter the character, then attempt to select via click and drag:

![backtick](https://user-images.githubusercontent.com/115237/155845155-5b70e751-3d9f-46c3-9a4b-e01d47970a80.gif)

**Comment by silverwind** [comment]
Safari 15 also shows the bug.

**Comment by Ionaru** [comment]
Looks like it's a macOS issue then. Even on Firefox I could not reproduce it.

That underline under the character, what does it mean?
It might mean that is has not actually 'typed' the character yet, because <kbd>`</kbd> is usually used as a dead key (needs <kbd>Space</kbd> to be typed.)

I'm seeing the same behaviour here: https://medium.com/@scr34mz/make-your-mac-keyboard-work-on-medium-and-others-editors-without-dead-keys-issues-french-keyboard-4666b72fa2ae

So what I gather from that article is that the <kbd>`</kbd> with the underline in your video isn't real input yet, but it does become real once you hit <kbd>Space</kbd>, then the selection should work as normal.

**Comment by silverwind** [comment]
Might be related to the combinator input behaviour of the backtick, but the deletion on selection is still unexpected and does not happen in a `<textarea>`. I use backticks a lot in markdown and often leave unterminated ones open and any kind of selection action in the document destroys test between start point of the selection and that "unresolved" backtick.

Here's another example with text before the backtick and selection starting on that text:

![backtick2](https://user-images.githubusercontent.com/115237/155845883-1815fb77-0a7c-4be5-989d-dc6d6143222c.gif)

**Comment by Ionaru** [comment]
Can you try the same on https://codemirror.net/ and https://codemirror.net/6/ for me?

This might help narrow it down.

**Comment by silverwind** [comment]
Happens in https://codemirror.net/mode/markdown/index.html too, so it seems it's a CodeMirror bug. Report there?

**Comment by silverwind** [comment]
Opened https://github.com/codemirror/CodeMirror/issues/6893

**Comment by silverwind** [comment]
CodeMirror 5.65.8 is released with this fixed.

**Comment by Ionaru** [comment]
Awesome! I'll made an update with that version included :)

**Comment by silverwind** [comment]
You don't actually have to because semver range `^5.60.4` matches the new version already :)
