### ISSUE TITLE
Cursor jumps around when editing text on Mobile

### ISSUE THREAD

**Issue by Hawkers** [Ionaru/easy-markdown-editor#77]
**Describe the bug**
The cursor does not always remain where the user intends.

**To Reproduce**
1. Open Chrome mobile
2. Type something at the end of the document
3. Tap after a word higher in the document and press space
4. Cursor will jump back to end of document

**Expected behavior**
The cursor should remain

** Version information **
- OS: Android
- Browser: Chrome 73
- EasyMDE 2.5.1

**Comment by chrisvel** [comment]
This is a serious issue. Same happens to me where cursor always jumps to the end of the document no matter what. Android also.

**Comment by Ionaru** [comment]
Was not able to reproduce
- OS: Android 9
- Browser: Chrome 76
- EasyMDE 2.8.0
- GBoard 8.6.10

Do you guys have the same problem in the editors on <https://easymde.tk>?
What keyboard are you using?

**Comment by chrisvel** [comment]
- OS: Android 8.0.0
- Browser: Chrome 76.0.3809.132
- EasyMDE: 2.8.0 

Strange thing is that I just installed Firefox on the same phone and it works fine, no issues. So it must be Chrome related only.

**Comment by ericek111** [comment]
Same here, EasyMDE 2.8.0

* OS: Android 8.1.0 (Lineage OS)
* Browser: Chrome 77
* EasyMDE: 2.8.0
* AOSP keyboard

It looks like some kind of optimization. Perhaps the input text is rendered before it's actually inserted into the HTML element? Cursor jumps erratically and it's a pain to use.

**Comment by daleharvey** [comment]
* Android Pixel 4
 * Android 10
 * Chrome 78

I see the same issue in Firefox, there seems to be a few issues editing on mobile and cant figure out how to trigger them reliably or how to seperate them but the 2 main things I see happen are my edits are constantly undone, and on pressing return the cursor goes to the start of the line

**Comment by Ge-lx** [comment]
* OnePlus 5T (A5010)
* Android 9
* Chrome 80.0.3987.149

I am also experiencing this bug and it makes for a very bad user experience. From my testing it seems that the editor is not correctly setting the internal cursor position when the user taps somewhere in the document.
It works fine, when using the cursor key (via remote debugging) or a mouse to interact with the document. While debugging this I saw, that CodeMirror is listening for `touchend` events to update the cursor position in response to user input on mobile.

The problem is, that sometimes the `touchend` event is not fired.
You should be able to see for yourself by registering event listeners like:
```javascript
window.addEventListener('touchend', () => console.log('touchend '))
window.addEventListener('touchstart', () => console.log('touchstart'))
```
Some googling led me to this [unfixed Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=464579), which could be causing this issue: When the target element of a `touchstart` is removed from the DOM while the touch is in progress, no `touchend` will be fired.

The problem would then be, that EasyMDE removes elements from the DOM, that have been the target of `touchstart` events, so that the corresponding `touchend` never fires.

**Comment by paxter** [comment]
This is still a huge problem on mobile devices and should be addressed as soon as possible.

**Comment by Ionaru** [comment]
Like @Ge-lx said, this is a CodeMirror issue, there's not really anything that can be done at this end. Upvote https://github.com/codemirror/CodeMirror/issues/5844 if you want to see it fixed.

**Comment by OnGe333** [comment]
There is word that CodeMirror 6 should have more robust mobile support (see: https://github.com/codemirror/CodeMirror/issues/5844 ). Maybe updating to CodeMirror 6 would fix this issue.
